services:
  forum:
    build: . # Build l'image
    ports:
      - "8082:8082" # Expose le port 8082 du conteneur
    environment:
      - ENV=production # Active le mode production dans l'app Go
      - PORT=8082 # Port
    volumes:
      - ./database:/app/database
      - ./uploads:/app/uploads
